package com.foreveross.atwork.infrastructure.plugin.zoom

enum class ZoomMeetingStatusProxy {

    MEETING_STATUS_IDLE,
    MEETING_STATUS_CONNECTING,
    MEETING_STATUS_WAITINGFORHOST,
    MEETING_STATUS_INMEETING,
    MEETING_STATUS_DISCONNECTING,
    MEETING_STATUS_RECONNECTING,
    MEETING_STATUS_FAILED,
    MEETING_STATUS_IN_WAITING_ROOM,
    MEETING_STATUS_WEBINAR_PROMOTE,
    MEETING_STATUS_WEBINAR_DEPROMOTE,
    MEETING_STATUS_UNKNOWN;


}